service: webhook

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  environment:
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "arn:aws:logs:eu-west-2:*:*"

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    timeout: 90
    memorySize: 256

plugins:
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 4001
    port: 4001
