service: webhook

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

functions:
  webhookHandler:
    handler: src/handler.webhookHandler
    events:
      - http:
          path: webhook
          method: post
          cors: true

plugins:
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 4001
    port: 4001
