service: webhook

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "arn:aws:logs:eu-west-2:*:*"

functions:
  webhookHandler:
    handler: src/handler.webhookHandler
    events:
      - http:
          path: webhook
          method: post
          cors: true

plugins:
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 4001
    port: 4001
